### ISSUE TITLE
error in launch in mac

### ISSUE THREAD

**Issue by sajjadintel** [spirinvladimir/logcat#6]
Hi,
when i start library in mac i see this error:

```
➜  ~ logcat
Logcat avalible at: http://localhost:59725
/usr/local/lib/node_modules/logcat/lib/check.js:8
        return has(line, error)
        ^

ReferenceError: has is not defined
    at /usr/local/lib/node_modules/logcat/lib/check.js:8:9
    at Array.map (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/logcat/lib/check.js:7:18)
    at Socket.<anonymous> (/usr/local/lib/node_modules/logcat/index.js:16:3)
    at Socket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by stuartaylward** [comment]
I get the same error!
